/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Participant = IDL.Record({
  'name' : IDL.Text,
  'dates' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
  'getSortedParticipantsByAvailability' : IDL.Func(
      [],
      [IDL.Vec(Participant)],
      ['query'],
    ),
  'updateAvailability' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Participant = IDL.Record({
    'name' : IDL.Text,
    'dates' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
    'getSortedParticipantsByAvailability' : IDL.Func(
        [],
        [IDL.Vec(Participant)],
        ['query'],
      ),
    'updateAvailability' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };